### ISSUE TITLE
why use vue

### ISSUE THREAD

**Issue by atayeem** [TheRandomMelon/services-site#1]
This might be a dumb question, I don't know much about web development, but can't you serve this website with pure HTML? I think all the features of the main page can be done with pure HTML and CSS. Like I'd think the framework is just creating more CPU overhead in order to build the page every time it loads, and more network usage to load the framework itself, and more network usage to not only load the HTML elements, but also the scripting to construct the HTML elements.

**Comment by ByteOfMelon** [comment]
got lazy lol, cba to change it
